"""Drop customer_name & total_amount from orders

Revision ID: 86628b3c24ff
Revises: 3be9da7f1d0a
Create Date: 2025-06-12 18:16:23.242683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86628b3c24ff'
down_revision = '3be9da7f1d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
       
        batch_op.drop_column('total_amount')
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.LargeBinary(length=128),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('total_amount', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
